# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 7

    border_size = 1

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(ffffffff) rgba(ffffff00) 45deg
    col.inactive_border = rgba(595959aa)
    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = true

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {

    

    screen_shader = ~/.config/hypr/shaders/contrast.frag
    rounding = 3
    rounding_power = 3

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = false
        range = 3
        render_power = 2
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 2
        passes = 3
        xray = false
        vibrancy = 0.1696

    

    }


}

